repos:
  - repo: https://github.com/Trim21/pre-commit-hooks
    rev: 5685ac183889dcafd0ea6c9dc3df211274554ec2  # frozen: v0.2.2
    hooks:
      - id: yamlfmt
      - id: poetry-check-lock
      - id: find-trailing-comma

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      # check for file bigger than 500kb
      - id: check-added-large-files
      - id: check-yaml
