# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
      - "*"
    exclude:
      - "renovate/*"

jobs:
  - job: "Test"
    pool:
      vmImage: "ubuntu-latest"

    strategy:
      matrix:
        Python36:
          python.version: "3.6"
        Python37:
          python.version: "3.7"
        Python38:
          python.version: "3.8"

    steps:
      - template: python/install-poetry-project.yaml
        parameters:
          python_version: $(python.version)
          extras: [ pre_commit ]

      - template: python/pre-commit.yaml
